### ISSUE TITLE
Add github publisher 

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#10]
We need github publisher. This will create issues in specified repository present in configurations.

```yml
feature: "Add gitlab publisher"
description: ""

configuration:
  cliRepo:
    type: github
    repo: microplan-xyz/microplan
    assignee: scriptnull # optional, can also be given in the plan
    milestone: some-milestone #optional, can also be given in the plan

plans:
  - title: "Add gitlab publisher"
    description: "We need publisher for gitlab"
    assignee: "argonlaser"
    in: cliRepo
```
