### ISSUE TITLE
microplan checklist

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#102]
Currently we have lot of information inside the plan file as YML or JSON etc.

I would like the ability to transform whatever is inside the plan file into some other meaning full form ( like a checklist ) 

This will enable workflows like below in `plan.yml` file

```yml
plans:

  - title: "Bootstrap CLI"
    description: "Do `npm init` and use commander.js to build the CLI"
    in: githubCli

  - title: "Discussion on backend framework"
    description: We are confused between using express.js and hapi. So lets discuss about it with benchmarks.
    in:
      - gitlabBackend

  - title: "Add microplan link command"
    in: githubCli
    description: Add the correct link
```

```bash 
$ microplan checklist plan.yml
- [ ] __1__ Bootstrap CLI
- [ ] __2__ Discussion on backend framework
- [ ] __3__ Add microplan link command
```

User could copy the checklist that he got from the stdout and use it

Even better way of doing it would be having a `microplan template` command instead of `microplan checklist` command

```bash
$ microplan template plan.yml checklist.template
```

checklist.template file will be a file, having [underscore style templating content](http://underscorejs.org/#template)
