### ISSUE TITLE
Assign muiltiple users 

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#50]
Currently we support only single assignee support in github and gitlab. 

We need to try out multiple assignees

**Comment by argonlaser** [comment]
Are we going to have CSV for the multiple assignees in the yaml?

**Comment by scriptnull** [comment]
nope. We will use yml array format and string format interchangably

For singly user, yml will look like
```yml
  - title: ....
    description: ....
    assignee: scriptnull
```

For multiple user, yml willl look like 
```yml
  - title: ....
    description: ....
    assignee:
      - argonlaser
      - scriptnull
```
